@page "/users/new"
@using siare.Shared.Entities
@inject HttpClient Http
@inject NavigationManager NavigationManager

<h1>New User</h1>

<p>@errorMessage</p>

<EditForm Model="@newUser" OnValidSubmit="HandleValidSubmit">
  <DataAnnotationsValidator />
  <ValidationSummary />

  <label for="userid">User ID:</label>
  <InputNumber id="userid" @bind-Value="newUser.UserId" class="form-control" placeholder="Userid" />
  <label for="username">Username:</label>
  <InputText id="username" @bind-Value="newUser.Username" class="form-control" placeholder="Username" />
  <label for="password">Password:</label>
  <InputText id="password" @bind-Value="newUser.PasswordHash" type="password" class="form-control" placeholder="Password" />
  <label for="email">Email:</label>
  <InputText id="email" @bind-Value="newUser.Email" type="email" class="form-control" placeholder="Email" />

  <button type="submit" class="btn btn-primary">Create User</button>
  <button class="btn btn-secondary" @onclick="GoBack">Go Back</button>
</EditForm>

@code {
  private User newUser = new User() { Username = "", PasswordHash = "", Email = "" };
  private string errorMessage = "";

  private async Task HandleValidSubmit()
  {
    try
    {
      var response = await Http.PostAsJsonAsync("api/Users", newUser);
      if (response.IsSuccessStatusCode)
      {
        NavigationManager.NavigateTo("/users");
      }
      else if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
      {
        errorMessage = "There was an issue with your submission. Please check the data and try again.";
      }
      else
      {
        errorMessage = "An unexpected error occurred.";
      }
    }
    catch (Exception ex)
    {
      errorMessage = $"Exception caught: {ex.Message}";
    }
  }

  private void GoBack()
  {
    NavigationManager.NavigateTo("/users");
  }
}
